#include "nginx/config_generator.hpp"

#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <stdexcept>

#include "util/logger.hpp"

namespace kp {
namespace {
constexpr std::string_view kComponent = "config_generator";
}  // namespace

ConfigGenerator::ConfigGenerator(std::string output_path) : output_path_(std::move(output_path)) {}

std::string ConfigGenerator::render(const std::vector<Route>& routes) {
  std::ostringstream out;
  out << "# AUTO-GENERATED by kingdom-proxy-api. Do not edit by hand --\n"
         "# this file is regenerated and overwritten whenever routes change.\n\n";

  for (const auto& route : routes) {
    if (!route.enabled) continue;

    // path_prefix is validated at the API boundary (see api/server.cpp) to
    // contain only safe URL-path characters, so it's fine to interpolate
    // directly into the generated config.
    const std::string location =
        !route.path_prefix.empty() && route.path_prefix.back() == '/'
            ? route.path_prefix
            : route.path_prefix + "/";
    const std::string var_name = std::format("kp_upstream_{}", route.id);

    out << std::format("location {} {{\n", location);
    // Assigning the upstream to a variable (rather than a literal in
    // proxy_pass) forces nginx to resolve the container name via the
    // `resolver` directive on every request instead of caching the IP from
    // when this config was loaded -- see nginx.baseline.conf. That's what
    // lets a route survive the target container being restarted.
    out << std::format("    set ${} \"http://{}:{}\";\n", var_name, route.container_name,
                        route.container_port);
    // A trailing slash on proxy_pass replaces the matched location prefix
    // with "/" (i.e. strips it); omitting it forwards the original URI
    // unchanged, prefix included.
    out << (route.strip_prefix ? std::format("    proxy_pass ${}/;\n", var_name)
                                : std::format("    proxy_pass ${};\n", var_name));
    out << "    proxy_http_version 1.1;\n"
           "    proxy_set_header Host $host;\n"
           "    proxy_set_header X-Real-IP $remote_addr;\n"
           "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
           "    proxy_set_header X-Forwarded-Proto $scheme;\n"
           "    proxy_set_header Upgrade $http_upgrade;\n"
           "    proxy_set_header Connection $connection_upgrade;\n"
           "}\n\n";
  }

  return out.str();
}

void ConfigGenerator::write(const std::vector<Route>& routes) const {
  const std::string rendered = render(routes);
  const std::filesystem::path final_path(output_path_);
  const std::filesystem::path tmp_path = final_path.string() + ".tmp";

  {
    std::ofstream out(tmp_path, std::ios::trunc);
    if (!out) {
      throw std::runtime_error(std::format("failed to open '{}' for writing", tmp_path.string()));
    }
    out << rendered;
  }

  std::error_code error_code;
  std::filesystem::rename(tmp_path, final_path, error_code);
  if (error_code) {
    throw std::runtime_error(std::format("failed to move '{}' into place at '{}': {}",
                                          tmp_path.string(), final_path.string(),
                                          error_code.message()));
  }

  KP_LOG_INFO(kComponent, "wrote {} route(s) to '{}'", routes.size(), output_path_);
}

}  // namespace kp
