#include "nginx/config_generator.hpp"

#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <stdexcept>

#include "util/logger.hpp"

namespace kp {
namespace {
constexpr std::string_view kComponent = "config_generator";

// path_prefix is restricted (see is_valid_path_prefix in api/server.cpp) to
// [A-Za-z0-9._-] plus '/', and of those only '.' is an nginx regex
// metacharacter (matches any character) -- it's escaped here since
// path_prefix gets embedded in a `rewrite` regex below.
std::string escape_rewrite_regex(const std::string& path_prefix) {
  std::string escaped;
  escaped.reserve(path_prefix.size());
  for (char c : path_prefix) {
    if (c == '.') escaped += '\\';
    escaped += c;
  }
  return escaped;
}
}  // namespace

ConfigGenerator::ConfigGenerator(std::string output_path) : output_path_(std::move(output_path)) {}

std::string ConfigGenerator::render(const std::vector<Route>& routes) {
  std::ostringstream out;
  out << "# AUTO-GENERATED by kingdom-proxy-api. Do not edit by hand --\n"
         "# this file is regenerated and overwritten whenever routes change.\n\n";

  for (const auto& route : routes) {
    if (!route.enabled) continue;

    // path_prefix is validated at the API boundary (see api/server.cpp) to
    // contain only safe URL-path characters, so it's fine to interpolate
    // directly into the generated config.
    const std::string location =
        !route.path_prefix.empty() && route.path_prefix.back() == '/'
            ? route.path_prefix
            : route.path_prefix + "/";
    const std::string var_name = std::format("kp_upstream_{}", route.id);

    out << std::format("location {} {{\n", location);
    // Assigning the upstream to a variable (rather than a literal in
    // proxy_pass) forces nginx to resolve the container name via the
    // `resolver` directive on every request instead of caching the IP from
    // when this config was loaded -- see nginx.baseline.conf. That's what
    // lets a route survive the target container being restarted. This must
    // come *before* the `rewrite ... break` below: `break` stops the
    // rewrite module (which is also what implements `set`) from running
    // any of its own directives that follow it in the same location, so a
    // `set` placed after a `break` would silently never execute, leaving
    // the variable uninitialized and the request failing with a 500.
    out << std::format("    set ${} \"http://{}:{}\";\n", var_name, route.container_name,
                        route.container_port);
    if (route.strip_prefix) {
      // nginx has a documented special case: when proxy_pass's value
      // contains a variable, the URI part it's known for at config-parse
      // time is irrelevant -- nginx *always* forwards the original request
      // URI unchanged, prefix included, no matter what follows the
      // variable (a trailing "/" there is silently ignored). Since a
      // variable is required here to get per-request DNS resolution,
      // prefix stripping has to happen separately, via `rewrite ... break`,
      // before proxy_pass ever sees the URI.
      // https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
      out << std::format("    rewrite ^{}/(.*)$ /$1 break;\n", escape_rewrite_regex(route.path_prefix));
    }
    // No URI part after the variable: nginx forwards whatever the current
    // request URI is -- the original one, or the one `rewrite` produced
    // above -- to the upstream unchanged.
    out << std::format("    proxy_pass ${};\n", var_name);
    out << "    proxy_http_version 1.1;\n"
           "    proxy_set_header Host $host;\n"
           "    proxy_set_header X-Real-IP $remote_addr;\n"
           "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
           "    proxy_set_header X-Forwarded-Proto $scheme;\n"
           "    proxy_set_header Upgrade $http_upgrade;\n"
           "    proxy_set_header Connection $connection_upgrade;\n"
           "}\n\n";
  }

  return out.str();
}

void ConfigGenerator::write(const std::vector<Route>& routes) const {
  const std::string rendered = render(routes);
  const std::filesystem::path final_path(output_path_);
  const std::filesystem::path tmp_path = final_path.string() + ".tmp";

  {
    std::ofstream out(tmp_path, std::ios::trunc);
    if (!out) {
      throw std::runtime_error(std::format("failed to open '{}' for writing", tmp_path.string()));
    }
    out << rendered;
  }

  std::error_code error_code;
  std::filesystem::rename(tmp_path, final_path, error_code);
  if (error_code) {
    throw std::runtime_error(std::format("failed to move '{}' into place at '{}': {}",
                                          tmp_path.string(), final_path.string(),
                                          error_code.message()));
  }

  KP_LOG_INFO(kComponent, "wrote {} route(s) to '{}'", routes.size(), output_path_);
}

}  // namespace kp
